version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: miac_user
      POSTGRES_PASSWORD: miac29
      POSTGRES_DB: miac_db
    ports:
      - "5432:5432"
  django:
    build:
      context: .
    ports:
      - "8001:8000"
    depends_on:
      - postgres-db
